knpu_oauth2_client:
    clients:
            vkontakte:
                # must be "vkontakte" - it activates that type!
                type: vkontakte
                # add and configure client_id and client_secret in parameters.yml
                client_id: '%env(OAUTH_VKONTAKTE_CLIENT_ID)%'
                client_secret: '%env(OAUTH_VKONTAKTE_CLIENT_SECRET)%'
                # a route name you'll create
                redirect_route: connect_vkontakte_check
                redirect_params: {}
