nelmio_cors:
    defaults:
#       origin_regex: true
        allow_credentials: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST']
        allow_headers: ['Content-Type', 'Authorization','X-AUTH-TOKEN',]
#       expose_headers: ['Link']
        max_age: 0
    paths:
        '^/': ~
