DateTime:
    type: custom-scalar
    config:
        serialize:    ["App\\Service\\GraphQL\\DateTimeType", "serialize"]
        parseValue:   ["App\\Service\\GraphQL\\DateTimeType", "parseValue"]
        parseLiteral: ["App\\Service\\GraphQL\\DateTimeType", "parseLiteral"]