DateTime:
    type: custom-scalar
    config:
        serialize:    ["App\\GaphQL\\DateTimeType", "serialize"]
        parseValue:   ["App\\GaphQL\\DateTimeType", "parseValue"]
        parseLiteral: ["App\\GaphQL\\DateTimeType", "parseLiteral"]