Mutation:
    type: object
    config:
        fields:
               mutationProfile:
                                 description: "Profile Entity Mutation"
                                 type: Profile!
                                 resolve: "@=service('profile.service').mutationProfile(args['input'])"
                                 args:
                                     input:
                                          type: "MutationProfileInput"


               singleUploadPhoto:
                                 description: "Mutation for upload file"
                                 type: 'Photo!'
                                 resolve: "@=service('file.service').singleUploadFile(args['file'])"
                                 args:
                                      file: 'FileUpload!'

               changeAvatars:
                                 description: "Mutation for change avatar"
                                 type: 'Profile!'
                                 resolve: "@=service('file.service').changeAvatars(args['file'])"
                                 args:
                                      file: 'FileUpload!'

               addProfileService:
                                 description: "Mutation for add new service"
                                 type: 'ProfileServices!'
                                 resolve: "@=service('services.profile.service').addProfileService(args['input'])"
                                 args:
                                      input:
                                           type: 'ProfileServiceInput'

               changeActiveProfileService:
                                 description: "Mutation for change status service"
                                 type: 'ProfileServices!'
                                 resolve: "@=service('services.profile.service').changeActiveProfileService(args['input'])"
                                 args:
                                     input:
                                          type: 'changeActiveProfileService'

MutationProfileInput:
    type: input-object
    config:
        fields:
            id:
                description: "Id profile for change"
                type: "Int!"
            title:
                description: "New title"
                type: "String"
            description:
                description: "New description"
                type: "String"
            address:
                description: "New addres"
                type: "Int"
            city:
                description: "New city"
                type: "Int"

ProfileServiceInput:
    type: input-object
    config:
        fields:
#             profile:
#                 description: "Id profile for add new service"
#                 type: "Int!"
             service:
                 description: "Id service for add new service"
                 type: "Int!"
             price:
                 description: "Price for add new service"
                 type: "Float!"

changeActiveProfileService:
    type: input-object
    config:
        fields:
              profileService:
                      description: "Id service for change service"
                      type: "Int!"
              active:
                      description: "Status active"
                      type: "Boolean!"