Mutation:
    type: object
    config:
        fields:
               mutationProfile:
                                 description: "Profile Entity Mutation"
                                 type: Profile!
                                 resolve: "@=service('profile.service').mutationProfile(args['input'])"
                                 args:
                                     input:
                                          type: "MutationProfileInput"


               singleUploadPhoto:
                                 type: 'Photo!'
                                 resolve: "@=service('file.service').singleUploadFile(args['file'])"
                                 args:
                                      file: 'FileUpload!'

               changeAvatars:
                                 type: 'Profile!'
                                 resolve: "@=service('file.service').changeAvatars(args['file'])"
                                 args:
                                      file: 'FileUpload!'


MutationProfileInput:
    type: input-object
    config:
        fields:
            id:
                type: "Int!"
            title:
                type: "String"
            description:
                type: "String"
            address:
                type: "Int"