Mutation:
    type: object
    config:
        fields:
               mutationProfile:
                                 description: "Profile Entity Mutation"
                                 type: Profile!
                                 resolve: "@=service('profile.service').mutationProfile(args['input'])"
                                 args:
                                     input:
                                          type: "MutationProfileInput"


               singleUploadPhoto:
                                 type: 'Photo!'
                                 resolve: "@=service('file.service').singleUploadFile(args['file'])"
                                 args:
                                      file: 'FileUpload!'

               changeAvatars:
                                 type: 'Profile!'
                                 resolve: "@=service('file.service').changeAvatars(args['file'])"
                                 args:
                                      file: 'FileUpload!'

               addProfileService:
                                 type: 'Profile!'
                                 resolve: "@=service('services.profile.service').addProfileService(args['file'])"
                                 args:
                                      input:
                                           type: 'ProfileService'


MutationProfileInput:
    type: input-object
    config:
        fields:
            id:
                description: "Id profile for change"
                type: "Int!"
            title:
                description: "New title"
                type: "String"
            description:
                description: "New description"
                type: "String"
            address:
                description: "New addres"
                type: "Int"
            city:
                description: "New city"
                type: "Int"

ProfileService:
    type: input-object
    config:
        fields:
#             profile:
#                 description: "Id profile for add new service"
#                 type: "Int!"
             service:
                 description: "Id service for add new service"
                 type: "Int!"
             price:
                 description: "Price for add new service"
                 type: "Float!"