Profile:
    type: object
    config:
        description: "Profile"
        fields:
              id:
                 type: "Int!"
                 description: "The unique ID of the profile."
              title:
                 type: "String"
                 description: "Title of the profile"
              description:
                 type: "String"
                 description: "Description of the profile"
              viewsCount:
                 type: "Int"
                 description: "Number of view of the profile"
              dateChanged:
                  type: "DateTime"
                  description: "Date changet of the profile"
              address:
                  type: "String"
                  description: "Address of the profile"
              avatar:
                  type: "String"
                  description: "Avatar of the profile"
              user:
                type: "User"
                description: "User of the profile"
              city:
                 type: "Cities"
                 description: "City of the profile"
              servises:
                 type: "[ProfileServices]"
                 description: "Services of the profile"
