Query:
    type: object
    config:
        description: "Menu ORM repository"
        fields:
#            menu:
#                description: "Getting menu for Process module"
#                type: "Menu"
#               resolve: "@=service('process.space.service').getMenu()"
            getProfile:
                description: "Getting profile for user"
                type: "Profile"
                resolve: "@=service('profile.service').getProfile()"

            getCities:
                description: "Getting cities for app"
                type: "[Cities]"
                resolve: "@=service('city.service').getCities()"

            getServices:
                description: "Getting services for app"
                type: "[Services]"
                resolve: "@=service('services.service').getServices()"