Query:
    type: object
    config:
        description: "Menu ORM repository"
        fields:
            menu:
                description: "Getting menu for Process module"
                type: "Menu"
#               resolve: "@=service('process.space.service').getMenu()"
            getProfile:
                description: "Getting profile for user"
                type: "Profile"
                resolve: "@=service('profile.service').getMenu()"