Profile:
    type: object
    config:
        description: "Profile"
        fields:
              id:
                 type: "Int!"
                 description: "The unique ID of the profile."
              title:
                 type: "String"
                 description: "Title of the profile"
              description:
                 type: "String"
                 description: "Description of the profile"