User:
    type: object
    config:
        description: "User"
        fields:
              id:
                 type: "Int!"
                 description: "The unique ID of the profile."
              username:
                 type: "String"
                 description: "Title of the profile"